# Generated by Django 2.0 on 2017-12-07 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_auto_20171204_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='companydetail',
            name='slug',
            field=models.SlugField(default='hello', unique=True),
            preserve_default=False,
        ),
    ]
